// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFiqruxMc4CunntMwfDXbUcmDNffMRRZo',
    appId: '1:109085224903:web:17b4c37a6668779631f3e2',
    messagingSenderId: '109085224903',
    projectId: 'speakaditya',
    authDomain: 'speakaditya.firebaseapp.com',
    storageBucket: 'speakaditya.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS_mQdUTWqmTr1TvRGNYvOODLgmQKR9Rw',
    appId: '1:109085224903:android:cd97db35ce67b9db31f3e2',
    messagingSenderId: '109085224903',
    projectId: 'speakaditya',
    storageBucket: 'speakaditya.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYHj14P08H0NtWSP8AhVAlwh3y61YAWHg',
    appId: '1:109085224903:ios:f34ca11592dbd9a531f3e2',
    messagingSenderId: '109085224903',
    projectId: 'speakaditya',
    storageBucket: 'speakaditya.firebasestorage.app',
    iosBundleId: 'com.example.speakup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYHj14P08H0NtWSP8AhVAlwh3y61YAWHg',
    appId: '1:109085224903:ios:f34ca11592dbd9a531f3e2',
    messagingSenderId: '109085224903',
    projectId: 'speakaditya',
    storageBucket: 'speakaditya.firebasestorage.app',
    iosBundleId: 'com.example.speakup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFiqruxMc4CunntMwfDXbUcmDNffMRRZo',
    appId: '1:109085224903:web:8cbf050c804e75b831f3e2',
    messagingSenderId: '109085224903',
    projectId: 'speakaditya',
    authDomain: 'speakaditya.firebaseapp.com',
    storageBucket: 'speakaditya.firebasestorage.app',
  );
}
