import 'package:flutter/material.dart';
import 'splash_screen.dart'; // Make sure to import your new file
import 'package:firebase_core/firebase_core.dart'; // Import Firebase Core
import 'firebase_options.dart'; // Ensure this file exists and is generated by FlutterFire CLI





void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Speak Up',
      theme: ThemeData(
        // This defines the default colors and styles for your app
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      // Set our new SplashScreen as the starting point of the app
      home: const SplashScreen(),
      debugShowCheckedModeBanner: false, // This removes the "Debug" banner
    );
  }
}
