name: namer_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  latlong2: ^0.9.1
  geodesy: ^0.10.2
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  firebase_core: ^3.15.2 # Must have for any Firebase project
  firebase_auth: ^5.1.1 # For user authentication
  cloud_firestore: ^5.0.2 # For the database
  flutter_compass: ^0.8.0
  permission_handler: ^11.3.1
  web_socket_channel: ^3.0.3
  mic_stream: ^0.7.2
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true